version: '3'
services:
  rdbms:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    environment:
      - JVM_OPTS=-Xms1024M -Xmx1024M
  redis:
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
  keycloak:
    image: jboss/keycloak:15.0.1
    ports:
      - "8089:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
 elastic:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
     ports:
       - "9200:9200"
       - "9300:9300"
     environment:
       - discovery.type=single-node